
vscode:
  extensions:
    - 42Crunch.vscode-openapi
tasks:
  - name: aws-cli-sso
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: 
      bash $THEIA_WORKSPACE_ROOT/scripts/aws-sso-for-gitpod.sh
    command:
      aws sso login